# version: '1.1'
services:
  # proxy:
    # image: 'registry.aibee.cn/qa/store_resource_management'
    # ports:
    #     - '80:80'
    # volumes:
    #     - '/var/run/docker.sock:/tmp/docker.sock:ro'
  db:
    image: mysql:8.0
    container_name: design-mysql
    ports:
      - 6603:3306
    expose:
      - 3306
    volumes:
      - /tmp/data/mysql_data:/usr/local/share/data
      #- './mysql/mysql:/var/lib/mysql'
      # - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./local_data/mysql_data:/usr/local/share/data
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: design_db

  app:
    image: backend:latest
    container_name: backend
    tty: true
    volumes: 
      - ./log:/home/store_log/
    # command: sh -c "bin/start_backend.sh"
  #   volumes:
  #     - ../../:/usr/src/app
  #     - type: volume
  #       source: qa019nfs
  #       target: /usr/src/static
  #       volume:
  #         nocopy: true
    ports:
      - 6688:6688
    links:
      - db
    depends_on:
      - db
    environment:
      MYSQL_HOST: design_mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: design_db
# volumes:
  # - './log:/home/store_log/'
#   qa019nfs:
#     driver_opts:
#       type: "nfs"
#       o: "addr=172.16.25.47,rw"
#       device: ":/data/backend-static"
