# version: '1.1'
services:
  # proxy:
    # image: 'registry.aibee.cn/qa/store_resource_management'
    # ports:
    #     - '80:80'
    # volumes:
    #     - '/var/run/docker.sock:/tmp/docker.sock:ro'
  db:
    image: mysql:8.0
    container_name: design-mysql
    ports:
      - 6603:3306
    expose:
      - 3306
    volumes:
      - /tmp/data/mysql_data:/usr/local/share/data
      #- './mysql/mysql:/var/lib/mysql'
      # - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./local_data/mysql_data:/usr/local/share/data
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: design_db

